/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CommissionerRole;

import Business.Chart.BarChartDemo;
import Business.Chart.PieChart_AWT;
import Business.Chart.Pie_Chart;
import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import Business.Organization.CommissionerOrganization;
import Business.Organization.InvestigatorOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.CaseWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.jfree.ui.RefineryUtilities;

/**
 *
 * @author raunak
 */
public class CommissionerMainWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private CommissionerOrganization commissionerOrganization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private Ecosystem system;
    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    public CommissionerMainWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, CommissionerOrganization organization, Enterprise enterprise,Ecosystem system) {
  
            initComponents();
            
            this.userProcessContainer = userProcessContainer;
            this.commissionerOrganization = organization;
            this.enterprise = enterprise;
            this.userAccount = account;
            this.system=system;
         
            populateRequestTable();
       
    }
    
    public void populateRequestTable(){
        //DefaultTableModel model = (DefaultTableModel) workRequestJTable.getModel();
        
       // model.setRowCount(0);
        for (WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[4];
            row[0] = request.getMessage();
            row[1] = request.getReceiver();
            row[2] = request.getStatus();
            //String result = ((CaseWorkRequest) request).getTestResult();
            //row[3] = result == null ? "Waiting" : result;
            
          //  model.addRow(row);
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        manageFIRButton = new javax.swing.JButton();
        manageReportJPanel = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel = new javax.swing.JLabel();
        manageAlarmReport = new javax.swing.JButton();
        attorneyJButton = new javax.swing.JButton();

        jLabel1.setText("Commisioner Work Area");

        manageFIRButton.setText("Manage FIR");
        manageFIRButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageFIRButtonActionPerformed(evt);
            }
        });

        manageReportJPanel.setText("Manage Report");
        manageReportJPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageReportJPanelActionPerformed(evt);
            }
        });

        jButton3.setText("Manage Case");

        jButton4.setText("Manage Investigator");

        jLabel.setText("jLabel2");

        manageAlarmReport.setText("Manage Public Report");
        manageAlarmReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageAlarmReportActionPerformed(evt);
            }
        });

        attorneyJButton.setText("Attorney");
        attorneyJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attorneyJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel)
                .addGap(328, 328, 328))
            .addGroup(layout.createSequentialGroup()
                .addGap(245, 245, 245)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(manageReportJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(manageFIRButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(manageAlarmReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(114, 114, 114)
                .addComponent(attorneyJButton)
                .addContainerGap(369, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(84, 84, 84)
                .addComponent(manageFIRButton)
                .addGap(26, 26, 26)
                .addComponent(manageReportJPanel)
                .addGap(9, 9, 9)
                .addComponent(jLabel)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(attorneyJButton))
                .addGap(34, 34, 34)
                .addComponent(manageAlarmReport)
                .addContainerGap(301, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageFIRButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageFIRButtonActionPerformed
        // TODO add your handling code here:
        ManageCommissionerFIRJPanel manageCommissionerFIRJPanel = new ManageCommissionerFIRJPanel(userProcessContainer,enterprise,userAccount,commissionerOrganization);
                    userProcessContainer.add("manageCommissionerFIRJPanel", manageCommissionerFIRJPanel);
CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                    layout.next(userProcessContainer);
    }//GEN-LAST:event_manageFIRButtonActionPerformed

    private void manageReportJPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageReportJPanelActionPerformed
       

  Pie_Chart demo = new Pie_Chart( "Mobile Sales",enterprise,commissionerOrganization);  
     demo.main();
      
     /*
      PieChart_AWT demo = new PieChart_AWT( "Mobile Sales",enterprise,commissionerOrganization);  
      demo.setSize( 560 , 367 );    
      RefineryUtilities.centerFrameOnScreen( demo );    
      
      demo.setVisible( true ); 
     */
          
     
      // BarChartDemo demo = new BarChartDemo("Bar Chart Demo",enterprise,commissionerOrganization);
      //  demo.pack();
       // RefineryUtilities.centerFrameOnScreen(demo);
       // demo.setVisible(true);
  //  ManageReport manageReport=new ManageReport(demo);

   //RefineryUtilities.centerFrameOnScreen( barChart_AWT );        
   // barChart_AWT.setVisible( true ); 
  
                  userProcessContainer.add("manageReportJPanel", manageReportJPanel);
CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                    layout.next(userProcessContainer);
    }//GEN-LAST:event_manageReportJPanelActionPerformed

    private void manageAlarmReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageAlarmReportActionPerformed
        // TODO add your handling code here:
        CommissionerPublicWorkAreaJPanel commissionerPublicWorkAreaJPanel=new CommissionerPublicWorkAreaJPanel(userProcessContainer,userAccount,commissionerOrganization,enterprise);
 
        userProcessContainer.add("commissionerPublicWorkAreaJPanel", commissionerPublicWorkAreaJPanel);
CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                    layout.next(userProcessContainer);
                    
        
    }//GEN-LAST:event_manageAlarmReportActionPerformed

    private void attorneyJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attorneyJButtonActionPerformed
        // TODO add your handling code here:
        ManageAttorneyJPanel attorneyJPanel=new ManageAttorneyJPanel(userProcessContainer,userAccount,commissionerOrganization,enterprise,system);
 
        userProcessContainer.add("ManageAttorneyJPanel", attorneyJPanel);
CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                    layout.next(userProcessContainer);
    }//GEN-LAST:event_attorneyJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton attorneyJButton;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageAlarmReport;
    private javax.swing.JButton manageFIRButton;
    private javax.swing.JButton manageReportJPanel;
    // End of variables declaration//GEN-END:variables
}
