/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CommissionerRole;

import Business.Chart.BarChartDemo;
import Business.Enterprise.Enterprise;
import Business.Organization.CommissionerOrganization;
import Business.UserAccount.UserAccount;
import java.awt.BorderLayout;
import javax.swing.JPanel;


/**
 *
 * @author PeaceFull
 */
public class ManageReportJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageReportJPanel
     */
     private JPanel userProcessContainer;
    private CommissionerOrganization commissionerOrganization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private BarChartDemo demo;
    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    public ManageReportJPanel(JPanel userProcessContainer,Enterprise enterprise, UserAccount account, CommissionerOrganization organization,BarChartDemo demo)  {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.commissionerOrganization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.demo=demo;
    
        
//jPanel1.setLayout(new java.awt.BorderLayout());

userProcessContainer.add(demo,BorderLayout.CENTER);
userProcessContainer.validate();    
    }

    
    /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PeaceFull
 */
 
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());
        add(jLabel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel;
    // End of variables declaration//GEN-END:variables
}
