/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AnalystRole;

import userinterface.AnalystRole.AnalystWorkAreaJPanel;
import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import Business.Organization.AnalystOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import UserInterface.SystemAdminWorkArea.SystemAdminWorkAreaJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;
import userinterface.AdministrativeRole.CriminalDirectoryJPanel;
import userinterface.AnalystRole.AnalystWorkAreaJPanel;

/**
 *
 * @author AkilP
 */
public class AnalystWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AnalystWorkAreaJPanel
     */
    
         private JPanel userProcessContainer;
    private UserAccount account;
    private AnalystOrganization analystOrganization;
    private Enterprise enterprise;
    
    public AnalystWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, AnalystOrganization analystOrganization, Enterprise enterprise) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
         initComponents();
         this.enterprise = enterprise;
        this.account = account;
        this.analystOrganization = analystOrganization;
        this.userProcessContainer = userProcessContainer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        manageFingerPrintButton = new javax.swing.JButton();
        manageDNARequest = new javax.swing.JButton();
        manageDispatchButton = new javax.swing.JButton();

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Manage Work Area");

        manageFingerPrintButton.setText("Manage Finger Print");
        manageFingerPrintButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageFingerPrintButtonActionPerformed(evt);
            }
        });

        manageDNARequest.setText("Manage DNA");
        manageDNARequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageDNARequestActionPerformed(evt);
            }
        });

        manageDispatchButton.setText("Manage Dispatch");
        manageDispatchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageDispatchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(353, 353, 353)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(manageFingerPrintButton)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(manageDispatchButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                        .addComponent(manageDNARequest, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(386, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addGap(121, 121, 121)
                .addComponent(manageDispatchButton)
                .addGap(60, 60, 60)
                .addComponent(manageDNARequest)
                .addGap(42, 42, 42)
                .addComponent(manageFingerPrintButton)
                .addContainerGap(492, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageDispatchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageDispatchButtonActionPerformed
        // TODO add your handling code here:
      ManageDispatchJPanel manageDispatchPanel = new ManageDispatchJPanel(userProcessContainer, enterprise ,analystOrganization,account);
     
       
       userProcessContainer.add(manageDispatchPanel,"ManageAnalystJPanel");
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_manageDispatchButtonActionPerformed

    private void manageFingerPrintButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageFingerPrintButtonActionPerformed
        // TODO add your handling code here:
        ManageAnalystFingerPrintJPanel manageAnalystFingerPrintJPanel = new ManageAnalystFingerPrintJPanel(userProcessContainer, enterprise ,account,analystOrganization);
        userProcessContainer.add(manageAnalystFingerPrintJPanel,"ManageAna1lystJPanel");
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageFingerPrintButtonActionPerformed

    private void manageDNARequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageDNARequestActionPerformed
        // TODO add your handling code here:
        ManageAnalystDNAJPanel manageDNAJPanel = new ManageAnalystDNAJPanel(userProcessContainer, enterprise ,account,analystOrganization);
        userProcessContainer.add(manageDNAJPanel,"ManageDNAJPanel");
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageDNARequestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton manageDNARequest;
    private javax.swing.JButton manageDispatchButton;
    private javax.swing.JButton manageFingerPrintButton;
    // End of variables declaration//GEN-END:variables
}
