/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.InvestigatorRole;

import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import Business.Organization.InvestigatorOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import UserInterface.SystemAdminWorkArea.ManageEnterpriseJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Aswat
 */
public class InvestigatorWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageCriminalInvestigation
     */
     private JPanel userProcessContainer;
    private UserAccount account;
    private InvestigatorOrganization investigatorOrganization;
    private Enterprise enterprise;
    
 public InvestigatorWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, InvestigatorOrganization investigatorOrganization, Enterprise enterprise) {
        initComponents();
        this.enterprise = enterprise;
        this.account = account;
        this.investigatorOrganization = investigatorOrganization;
        this.userProcessContainer = userProcessContainer;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        managePublicButton = new javax.swing.JButton();
        criminalInvestigationButton = new javax.swing.JButton();
        manageCommissionerButton = new javax.swing.JButton();
        manageAnalystButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Manage Criminal Information");

        managePublicButton.setText("Manage Public Location");
        managePublicButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managePublicButtonActionPerformed(evt);
            }
        });

        criminalInvestigationButton.setText("Manage Criminal Investigation");
        criminalInvestigationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criminalInvestigationButtonActionPerformed(evt);
            }
        });

        manageCommissionerButton.setText("Manage Commisioner Request");
        manageCommissionerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageCommissionerButtonActionPerformed(evt);
            }
        });

        manageAnalystButton.setText("Manage Analyst Request");
        manageAnalystButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageAnalystButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(347, 347, 347)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(387, 387, 387)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(criminalInvestigationButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(manageCommissionerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(manageAnalystButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(managePublicButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(302, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(75, 75, 75)
                .addComponent(managePublicButton)
                .addGap(44, 44, 44)
                .addComponent(criminalInvestigationButton)
                .addGap(38, 38, 38)
                .addComponent(manageAnalystButton)
                .addGap(34, 34, 34)
                .addComponent(manageCommissionerButton)
                .addContainerGap(336, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageAnalystButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageAnalystButtonActionPerformed
        // TODO add your handling code here:
        
           ManageAnalystJPanel manageAnalystPanel = new ManageAnalystJPanel(userProcessContainer, enterprise ,investigatorOrganization,account);
        userProcessContainer.add(manageAnalystPanel,"ManageAnalystJPanel");
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageAnalystButtonActionPerformed

    private void manageCommissionerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageCommissionerButtonActionPerformed
        // TODO add your handling code here:
        
        ManageCommisionerJPanel mc = new ManageCommisionerJPanel(userProcessContainer, enterprise ,investigatorOrganization,account);
        userProcessContainer.add("ManageComm", mc);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageCommissionerButtonActionPerformed

    private void managePublicButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managePublicButtonActionPerformed
        // TODO add your handling code here:
        
           ManagePublicLocationJPanel managePublicLocation = new ManagePublicLocationJPanel(userProcessContainer, enterprise ,investigatorOrganization,account);
        userProcessContainer.add(managePublicLocation,"ManageAnalystJPanel");
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_managePublicButtonActionPerformed

    private void criminalInvestigationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criminalInvestigationButtonActionPerformed
        // TODO add your handling code here:
        ManageCriminalInvestigationJPanel manageCriminalInvestigationJPanel = new ManageCriminalInvestigationJPanel(userProcessContainer, enterprise ,investigatorOrganization,account);
        userProcessContainer.add("manageCriminalInvestigationJPanel", manageCriminalInvestigationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_criminalInvestigationButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton criminalInvestigationButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageAnalystButton;
    private javax.swing.JButton manageCommissionerButton;
    private javax.swing.JButton managePublicButton;
    // End of variables declaration//GEN-END:variables
}
