/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AdministrativeRole;

import Business.Enterprise.Enterprise;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author PeaceFull
 */
public class AdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminJPanel
     */
    
      
    JPanel userProcessContainer;
    Enterprise enterprise;
    /** Creates new form AdminWorkAreaJPanel */
    public AdminJPanel(JPanel userProcessContainer, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
      //  valueLabel.setText(enterprise.getName());
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        managePublicJButton = new javax.swing.JButton();
        valueLabel = new javax.swing.JLabel();
        managePoliceJButton = new javax.swing.JButton();

        managePublicJButton.setText("Manage Public");
        managePublicJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managePublicJButtonActionPerformed(evt);
            }
        });

        valueLabel.setText("<value>");

        managePoliceJButton.setText("Manage Police");
        managePoliceJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managePoliceJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(301, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(valueLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(managePoliceJButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(managePublicJButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(126, 126, 126))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(valueLabel)
                .addGap(72, 72, 72)
                .addComponent(managePublicJButton)
                .addGap(63, 63, 63)
                .addComponent(managePoliceJButton)
                .addContainerGap(160, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void managePublicJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managePublicJButtonActionPerformed
        // TODO add your handling code here:
        
                
            /*       
        ManagePublicOrganizationJPanel adminPublicWorkAreaJPanel = new ManagePublicOrganizationJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("adminPublicWorkAreaJPanel", adminPublicWorkAreaJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
*/
    }//GEN-LAST:event_managePublicJButtonActionPerformed

    private void managePoliceJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managePoliceJButtonActionPerformed
        // TODO add your handling code here:
        
        /*
                   
        AdminPoliceWorkAreaJPanel adminPoliceWorkAreaJPanel = new AdminPoliceWorkAreaJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("adminPoliceWorkAreaJPanel", adminPoliceWorkAreaJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
*/
    }//GEN-LAST:event_managePoliceJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton managePoliceJButton;
    private javax.swing.JButton managePublicJButton;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
