/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.LabRole;

import Business.Enterprise.Enterprise;
import Business.Organization.LabOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Aswat
 */
public class LabAssistantWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LabAssistantWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    private LabOrganization labOrganization;
    private Enterprise enterprise;

    public LabAssistantWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, LabOrganization labOrganization, Enterprise enterprise) {
        initComponents();
        this.enterprise = enterprise;
        this.account = account;
        this.labOrganization = labOrganization;
        this.userProcessContainer = userProcessContainer;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageFingerPrintsButton = new javax.swing.JButton();
        manageDNAButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        manageFingerPrintsButton.setText("Manage Finger Prints");
        manageFingerPrintsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageFingerPrintsButtonActionPerformed(evt);
            }
        });

        manageDNAButton.setText("Manage DNA");
        manageDNAButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageDNAButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Lab Assistan Work Area");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(manageFingerPrintsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageDNAButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(233, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(187, 187, 187))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(97, 97, 97)
                .addComponent(manageFingerPrintsButton)
                .addGap(46, 46, 46)
                .addComponent(manageDNAButton)
                .addContainerGap(234, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageFingerPrintsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageFingerPrintsButtonActionPerformed
        // TODO add your handling code here:
        ManageFingerPrintJPanel manageFingerPrintJPanel = new ManageFingerPrintJPanel(userProcessContainer, enterprise, labOrganization, account);
        userProcessContainer.add("ManageFingerPrintJPanel", manageFingerPrintJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageFingerPrintsButtonActionPerformed

    private void manageDNAButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageDNAButtonActionPerformed
        // TODO add your handling code here:
        ManageDNAJPanel manageDNAJPanel = new ManageDNAJPanel(userProcessContainer, enterprise, labOrganization, account);
        userProcessContainer.add("ManageDNAJPanel", manageDNAJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageDNAButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageDNAButton;
    private javax.swing.JButton manageFingerPrintsButton;
    // End of variables declaration//GEN-END:variables
}
